language: python
dist: xenial
python:
- '3.6'
- '3.7'
- '3.8'
install:
  - pip install coveralls -r tests/requirements.txt
script:
  - pytest --cov=cawdrey tests/
after_success:
  - coveralls
deploy:
  provider: pypi
  user: DomDF
  on:
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_existing: true
  password:
    secure: dumMBMVtBP9QB27XlJVgGbib8S5mWEeufn4lHBphwRT2Sr4yKgUaWdqCEpvJU3FwXeDCEGbaLkkRxL/wlmzzgNrTRl/xpSaXi8qjMPdxXfn8FGjaFfdqZEhYLdBrX100vDxcNehQpHi9sfLRsE4ttdHkn8YtamOp1KKPQOQpuZn5vvig602Ik9q7Lscm3jbhbWtomAqY1o7x95Tdj8RmpGX3c+76+eKnFHgGDaD4LiZTT4V1lNi84GkXaiEsDebPvPT2ki1xaeOhUyI4SeJrywGKPLqKYO1/BXdKWwX0HgUtav5KXdAqmLL8hH0ysrxKkKybkMXmPr63NU7pSTwYVWf2FTZe+QarUCQoToFtRNEPNf3/Serwx8TP6f8AraibZeeGrwK4CDvCl9qVQCsMr5xcB8WDPgLUCbF06Wrvb9umy6m5TAlX02YGnFjjBkciUjUpAsoi0JslaXQXSYWVj/PzEHMYGEuITn8TZpbIRChQhLoj9hE5gpTJxkHPsidoUjg0S5v9oC7+XVjpGyaOVsWMIiy2gSNIYNSyLo1aXf7Rx2ZNQvQRrqP8KMcHtUiltUn1X56AeVOHrB36PuM0oHHV6oNsTL8xCccHyuIb2FthH7RukQox6hHDm3nPEh+seuFM6fu5cJLF2MEDrDOClZXVOLpYus4BqYRCI5Wgv/k=
