# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
  - 'pypy3'

arch:
  - amd64
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox -vv
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi
  - deploy_conda

jobs:
  allow_failures:
    - arch: arm64

  exclude:
    - python: '3.7'
      arch: arm64
    - python: '3.8'
      arch: arm64
    - python: '3.9-dev'
      arch: arm64
    - python: 'pypy3'
      arch: arm64

  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/cawdrey
        provider: pypi
        user: "DomDF"
        password:
          secure: dumMBMVtBP9QB27XlJVgGbib8S5mWEeufn4lHBphwRT2Sr4yKgUaWdqCEpvJU3FwXeDCEGbaLkkRxL/wlmzzgNrTRl/xpSaXi8qjMPdxXfn8FGjaFfdqZEhYLdBrX100vDxcNehQpHi9sfLRsE4ttdHkn8YtamOp1KKPQOQpuZn5vvig602Ik9q7Lscm3jbhbWtomAqY1o7x95Tdj8RmpGX3c+76+eKnFHgGDaD4LiZTT4V1lNi84GkXaiEsDebPvPT2ki1xaeOhUyI4SeJrywGKPLqKYO1/BXdKWwX0HgUtav5KXdAqmLL8hH0ysrxKkKybkMXmPr63NU7pSTwYVWf2FTZe+QarUCQoToFtRNEPNf3/Serwx8TP6f8AraibZeeGrwK4CDvCl9qVQCsMr5xcB8WDPgLUCbF06Wrvb9umy6m5TAlX02YGnFjjBkciUjUpAsoi0JslaXQXSYWVj/PzEHMYGEuITn8TZpbIRChQhLoj9hE5gpTJxkHPsidoUjg0S5v9oC7+XVjpGyaOVsWMIiy2gSNIYNSyLo1aXf7Rx2ZNQvQRrqP8KMcHtUiltUn1X56AeVOHrB36PuM0oHHV6oNsTL8xCccHyuIb2FthH7RukQox6hHDm3nPEh+seuFM6fu5cJLF2MEDrDOClZXVOLpYus4BqYRCI5Wgv/k=
        distributions: "sdist bdist_wheel"
        skip_existing: true
    - stage: deploy_conda
      python: "3.6"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        provider: script
        script: .ci/travis_deploy_conda.sh || return 1;
